emsize: 64
hidden_size: 512
num_layers: 2
dropout: 0.2
clip_norm: 5.0
epochs: 100
batch_size: 50
#log_interval: "all"
vocab_size: 20000
endure_times: 5
optim: "adam"
lr: 0.0001
#scheduler: "steplr"
#step_size: 1
#alpha: 0.95
text_reg: 1
